apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-microservice-demo
  title: Create Microservice demo
  description: scaffolder action to create micro-service
spec:
  owner: my-team
  type: service

  parameters:
    - title: Pick a template
      required:
        - templateRepoUrl
      properties:
        templateRepoUrl:
          title: Template Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - ahmadiesa-abu
            allowedRepos:
              - nodejs-template
              - python-template
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: fetch-template
      name: Fetch microservice template
      action: fetch:template
      input:
        url: ${{ parameters.templateRepoUrl }}
        targetPath: './repo-contents'

    - id: publish
      name: Fork microservice repo
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.microserviceName }} code repo
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: private
        defaultBranch: master
        sourcePath: ./repo-contents

    # - id: create-cloudify-deployment
    #   name: Create Cloudify Deployment
    #   action: cloudify:deployment:create-deployment
    #   input:
    #     deploymentName: ${{ parameters.deploymentName }}
    #     blueprintID: ${{ parameters.blueprintID }}
    #     deploymentInputs:
