apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-deployment-demo
  title: Create Deployment demo
  description: scaffolder action to create cloudify deployment
spec:
  owner: my-team
  type: service

  parameters:
    - title: Provide some simple information
      required:
        - deploymentName
        - blueprintID
      properties:
        deploymentName:
          title: Deployment Name
          type: string
          description: The name of Cloudify deployment
        blueprintID:
          title: Blueprint ID
          type: string
          description: The ID of Cloudify blueprint to create deployment from
          enum:
            - EC2-AWS-CFY
#             - test-input-types
#             - Backstage-AWS-CFY
#             - EC2-VPC
#             - Istio-AWS-CFY
        deploymentInputs:
          title: Deployment Inputs
          type: object
          description: The inputs to pass to Cloudify blueprint when creating the deployment
          properties:
            instance_type:
              title: ec2 instance type
              type: string
              enum:
                - t2.nano
                - t2.micro
                - t2.medium
                - t2.large
#             test_multiple_choice:
#               title: string choice of colors
#               type: string
#               enum:
#                 - White
#                 - Black
#                 - Yellow
#                 - Green
#                 - Blue
#                 - Red
#                 - Gray
  steps:
    - id: create-cloudify-deployment
      name: Create Cloudify Deployment
      action: cloudify:deployment:create-deployment
      input:
        deploymentName: ${{ parameters.deploymentName }}
        blueprintID: ${{ parameters.blueprintID }}
        deploymentInputs: ${{ parameters.deploymentInputs }}
